import Link from "next/link";

export const metadata = {
  title: "Create Next App by rpk",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div className="p-10">
      <h1 className="text-3xl font-bold">Home Page</h1>
      <div className="mt-5 text-lg">
        Welcome to our website! We are delighted to have you here. Explore our
        services, read our latest blogs, and feel free to reach out through our
        contact page. Enjoy your stay!
      </div>
    </div>
  );
}
